# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Study Documentation
email: aprilrinshan@gmail.com
description: I write about technology.
# this means to ignore newlines until "baseurl:"
# Write an awesome description for your new site here. You can edit this
# line in _config.yml. It will appear in your document head meta (for
# Google search results) and in your feed.xml site description.
twitter_username: shandrinadwi
github_username: rinashan
minimal_mistakes_skin: default
search: true

# Build settings
markdown: kramdown
remote_theme: mmistakes/minimal-mistakes
# Outputting
permalink: /:categories/:title/
paginate: 10 # amount of posts to show
paginate_path: /page:num/
timezone: # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones

include:
  - _pages

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

# Plugins (previously gems:)
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache

author:
  name   : "^_^"
  avatar : "/assets/images/bio-photo.jpg"
  bio    : "Hi, I'm Shandrina."
  location : "Indonesia"
  links:
    - label: "Website"
      icon: "fas fa-fw fa-link"
      url: "https://rinashan.github.io"
#    - label: "Twitter"
#      icon: "fab fa-fw fa-twitter-square"
#      url: "https://twitter.com/shandrinadwi"
#    - label: "Github"
#      icon: "fab fa-fw fa-github"
#      url: "https://github.com/rinashan"
    - label: Linkedin
      icon: "fab fa-fw fa-linkedin"
      url: "https://www.linkedin.com/in/shandrina-dwi-apriliyana-a30b241a5"
    - label: "Instagram"
      icon: "fab fa-fw fa-instagram"
      url: "https://instagram.com/riinashan"
    - label: Facebook
      icon: "fab fa-fw fa-facebook"
      url: "https://www.facebook.com/shandrina.apriliyana"


footer:
  links:
    - label: Linkedin
      icon: "fab fa-fw fa-linkedin"
      url: "https://www.linkedin.com/in/shandrina-dwi-apriliyana-a30b241a5"
    - label: "Instagram"
      icon: "fab fa-fw fa-instagram"
      url: "https://instagram.com/riinashan"
    - label: Facebook
      icon: "fab fa-fw fa-facebook"
      url: "https://www.facebook.com/shandrina.apriliyana"

comments:
  provider: "disqus"
  disqus:
    shortname: "shandrinadwiapriliyana"
  url: https://rinashan.github.io

defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true 
      read_time: true
      comments: true
      share: true
      related: true
      show_date: true
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true

category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/


# fixes "No GitHub API authentication" error
github: [metadata]

